version: '3.8' # Pode ser removido se estiver usando docker compose v2

services:
  informix:
    image: icr.io/informix/informix-developer-database:latest
    container_name: informix_db
    privileged: true
    ports:
      - "9088:9088" # Porta SQL
      - "9089:9089" # Porta DRDA
    environment:
      - LICENSE=accept
    volumes:
      - informix_data:/informix

volumes:
  informix_data:
    driver: local